# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ Large Hadron Migrator }
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["SoundCloud", "Rany Keddo", "Tobias Bielohlawek"]
  s.date = %q{2011-03-03}
  s.description = %q{Migrate large tables without downtime by copying to a temporary table in chunks. The old table is not dropped. Instead, it is moved to timestamp_table_name for verification.}
  s.email = %q{rany@soundcloud.com, tobi@soundcloud.com}
  s.files = [
    ".gitignore",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "large-hadron-migrator.gemspec",
    "lib/large_hadron_migration.rb",
    "spec/large_hadron_migration_spec.rb",
    "spec/migrate/add_new_column.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/soundcloud/large-hadron-migrator}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{online schema changer for mysql}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<activerecord>, ["= 2.3.5"])
      s.add_development_dependency(%q<activesupport>, ["= 2.3.5"])
      s.add_development_dependency(%q<rspec>, ["= 1.3.0"])
    else
      s.add_dependency(%q<activerecord>, ["= 2.3.5"])
      s.add_dependency(%q<activesupport>, ["= 2.3.5"])
      s.add_dependency(%q<rspec>, ["= 1.3.0"])
    end
  else
    s.add_dependency(%q<activerecord>, ["= 2.3.5"])
    s.add_dependency(%q<activesupport>, ["= 2.3.5"])
    s.add_dependency(%q<rspec>, ["= 1.3.0"])
  end
end

