#!/bin/sh

set -e
set -u

source .config

lhmkill() {
  ps -ef | gsed -n "/[m]ysqld.*lhm-cluster/p" | awk '{ print $2 }' | xargs kill
  sleep 5
}

echo stopping other running mysql instance
launchctl remove com.mysql.mysqld || { echo launchctl did not remove mysqld; }
mysqladmin shutdown || { echo mysqladmin did not shut down anything; }

echo killing lhm-cluster
lhmkill

echo removing $basedir
rm -rf "$basedir"

echo setting up cluster
spec/config/setup-cluster

echo staring instances
mysqld --defaults-file="$basedir/master/my.cnf" 2>&1 >$basedir/master/lhm.log &
mysqld --defaults-file="$basedir/slave/my.cnf" 2>&1 >$basedir/slave/lhm.log &
sleep 5

echo running grants
spec/config/grants

trap lhmkill SIGTERM SIGINT

wait
