#!/usr/bin/env ruby

require "optparse"

settings = {
  :adapter   =>  "mysql",
  :database  =>  "large_hadron_migrator",
  :username  =>  "",
  :host      =>  "localhost"
}

options = OptionParser.new do |o|
  o.on("-h", "--help",                "Print the usage")                      { |o| puts options.to_s; exit }
  o.on("-d", "--database <database>", "Database [#{ settings[:database] }]")  { |o| settings[:database] = o }
  o.on("-u", "--username <username>", "Username [#{ settings[:username] }]")  { |o| settings[:username] = o }
  o.on("-n", "--hostname <hostname>", "Hostname [#{ settings[:host] }]")      { |o| settings[:host] = o }
  o.on("-p", "--password <password>", "Password")                             { |o| settings[:password] = o }
end

options.parse(ARGV)

def prefill
  cmd = "prefill -d%{database} -u%{username} -n%{host}" % settings
  cmd += " -p%{password}" % settings if settings[:password]

  system(cmd)
end

def fuzz
end

def migrate
end

def unfuzz
end

def verify
end

prefill
fuzz
migrate
unfuzz
verify
