#!/usr/bin/env ruby

require "trollop"
require "open3"
require "active_record"
require "tempfile"

class Prefill
  attr_accessor :opts

  def initialize
    self.opts = Trollop::options do
      opt :database, "The database", :default => "large_hadron_migrator"
      opt :username, "The username", :default => ""
      opt :host,     "The hostname", :default => "localhost", :short => "n"
      opt :password, "The password", :type => :string
      opt :adapter,  "The adapter",  :default => "mysql"
      opt :rows,     "Created rows", :default => 1_000_000
    end
  end

  def config
    self.opts.select do |key, value|
      [:database, :username, :host, :password, :adapter].include?(key)
    end
  end

  def run
    ActiveRecord::Base.establish_connection(config)

    # create_schema
    fill_table
  end

  def create_schema
    db "drop table if exists test"
    db %{
      create table test (
        id int(11) not null auto_increment,
        type varchar(10) not null,
        data text default null,
        created_at datetime default null,
        updated_at datetime default null,
        primary key (id)
      ) engine=innodb default charset=utf8 collate=utf8_unicode_ci
    }
  end

  def fill_table
    input = Tempfile.new("lhm-prefill")
    random = File.open("/dev/random")
    types = [:update, :delete, :static]

    opts[:rows].times do |i|
      time = Time.now.utc.strftime("%Y-%m-%d %H:%M:%S")
      data = [random.read(1024)].pack("m*").gsub("\n", "")

      input.write [i + 1, types.sample, data, time, "\\N\n"].join("\t")
    end

    input.flush
    input.chmod(0644)
    db "load data infile '%s' into table test" % input.path
  ensure
    random.close
    input.close
  end

private

  def db(cmd)
    ActiveRecord::Base.connection.execute(cmd)
  end

end

script = Prefill.new
script.run

exit 0 # script aborts on errors

