#!/usr/bin/env ruby

load File.expand_path("fuzz", File.dirname(__FILE__))

class FuzzPercona < Fuzz
  def migrate
    alter = "add column attachment varchar(10) not null default 'attachment'"
    `pt-online-schema-change u=,h=127.0.0.1,t=test \
       --alter "#{alter}" --database large_hadron_migrator --drop-old-table`
  end
end

if $0 == __FILE__
  fuzz = Fuzz.new
  fuzz.run

  exit 0 # script aborts on errors
end
