#!/usr/bin/env ruby

require "trollop"
require "open3"

class Fuzz
  attr_accessor :opts

  def initialize
    self.opts = Trollop::options do
      opt :database, "The database", :default => "large_hadron_migrator"
      opt :username, "The username", :default => ""
      opt :host,     "The hostname", :default => "localhost", :short => "n"
      opt :password, "The password", :type => :string
    end
  end

  def run
    prefill
    fuzz
    migrate
    unfuzz
    verify
  end

  def prefill
    cmd = "prefill -d%{database} -u%{username} -n%{host}" % self.opts
    cmd += " -p%{password}" % settings if self.opts[:password]

    execute(cmd)
  end

  def fuzz
  end

  def migrate
  end

  def unfuzz
  end

  def verify
  end

  private

    def execute(cmd)
      out, err, status = Open3.capture3(cmd)

      unless status.success?
        $stderr.puts "Could not run '#{ cmd }'"
        $stderr.puts err

        exit 1
      end

      return out
    end
end

script = Fuzz.new
exit script.run
