#!/usr/bin/env ruby

require "trollop"
require "open3"
require "active_record"
require "tempfile"

class Prefill
  attr_accessor :opts, :counts

  def initialize
    self.opts = Trollop::options do
      opt :database, "The database", :default => "lhm"
      opt :username, "The username", :default => ""
      opt :host,     "The hostname", :default => "localhost", :short => "n"
      opt :password, "The password", :type => :string
      opt :adapter,  "The adapter",  :default => "mysql"
      opt :rows,     "Created rows", :default => 1_000_000
    end
  end

  def config
    self.opts.select do |key, value|
      [:database, :username, :host, :password, :adapter].include?(key)
    end
  end

  def run
    ActiveRecord::Base.establish_connection(config)

    create_schema
    fill_table
    puts self.counts.inspect
  end

  def create_schema
    puts "create schema"
    db "drop table if exists test"
    db %{
      create table test (
        id int(11) not null auto_increment,
        type varchar(10) not null,
        data text default null,
        created_at datetime default null,
        updated tinyint(1) not null default 0,
        primary key (id)
      ) engine=innodb default charset=utf8 collate=utf8_unicode_ci
    }
  end

  def fill_table
    print "generate data"
    input = Tempfile.new("lhm-prefill")
    random = File.open("/dev/random")
    types = [:update, :delete, :static]
    self.counts = types.inject({}) { |memo, type| memo.merge(type => 0) }

    opts[:rows].times do |i|
      time = Time.now.utc.strftime("%Y-%m-%d %H:%M:%S")
      data = [random.read(1024)].pack("m*").gsub("\n", "")
      type = types.sample
      self.counts[type] += 1

      input.write [i + 1, type, data, time, "\\N\n"].join("\t")

      print "." if (i.to_f / opts[:rows]) % 0.1 == 0
    end
    puts

    input.flush
    input.chmod(0644)
    puts "load data into table"
    db "load data infile '%s' into table test" % input.path
  ensure
    random.close
    input.close
  end

private

  def db(cmd)
    ActiveRecord::Base.connection.execute(cmd)
  end

end

script = Prefill.new
script.run

exit 0 # script aborts on errors
